eureka:  
  client:
    serviceUrl:
      defaultZone: http://10.39.1.67:8761/eureka/
server:
  port: 18000
spring:
  datasource:
    url: jdbc:mysql://10.39.1.47/tbs
    username: root
    password: root
  redis:
    host: 127.0.0.1
    database: 5
  activemq:
    broker-url: tcp://10.39.1.47:61616
